#!/usr/bin/env bash
#This script displays a school file
file="School"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ -s "$file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
else
	echo "schoolfile does not exist"
fi
