#!/usr/bin/env bash
#This script displays a school file

if [ -e "school" ]
then
echo "School file exists"
if [ -s "school" ]
then
 echo "School file is not empty"
 else
echo "school"
fi
if [ -f "school" ]
 then
echo "School is a regular file"
fi
